import { create } from 'zustand';

// A Guided Session is an ordered queue of exercises a warrior commits to
// up front — either hand-picked in the Exercise Picker or generated by
// Swift Forge — then works through one at a time in Strength Log, with
// the rest timer automatically advancing to the next exercise once the
// planned sets for the current one are done.
//
// Deliberately NOT persisted to AsyncStorage: if the app is killed
// mid-session the queue is lost. That's the same risk profile a normal
// (non-guided) Strength Log session already has today — there's no
// crash-recovery there either. Keeping this as plain in-memory Zustand
// state avoids adding that complexity for a feature that's meant to be
// one focused, uninterrupted training block anyway.
export interface GuidedExercise {
  exerciseId: string;
  exerciseName: string;
  category: string;
  // Swift Forge already knows a target sets/reps scheme per exercise;
  // hand-picked sessions from the Exercise Picker don't, so these are
  // optional and Strength Log falls back to "advance whenever the
  // warrior taps Next" if they're absent. targetReps is a string, not a
  // number — Swift Forge's generator expresses reps as a range (e.g.
  // "8-10"), not a single value, same as it already renders in its own
  // "SETS×REPS" battle plan display.
  targetSets?: number;
  targetReps?: string;
}

interface GuidedSessionStore {
  queue: GuidedExercise[];
  currentIndex: number;
  isActive: boolean;

  startSession: (queue: GuidedExercise[]) => void;
  // Moves to the next exercise and returns it, or returns null (and
  // marks the session inactive) once the queue is exhausted.
  advance: () => GuidedExercise | null;
  endSession: () => void;
  getCurrent: () => GuidedExercise | null;
  getUpNext: () => GuidedExercise | null;
  getProgress: () => { current: number; total: number };
}

export const useGuidedSessionStore = create<GuidedSessionStore>((set, get) => ({
  queue: [],
  currentIndex: 0,
  isActive: false,

  startSession: (queue) => {
    set({ queue, currentIndex: 0, isActive: queue.length > 0 });
  },

  advance: () => {
    const { queue, currentIndex } = get();
    const nextIndex = currentIndex + 1;
    if (nextIndex >= queue.length) {
      set({ isActive: false });
      return null;
    }
    set({ currentIndex: nextIndex });
    return queue[nextIndex];
  },

  endSession: () => {
    set({ queue: [], currentIndex: 0, isActive: false });
  },

  getCurrent: () => {
    const { queue, currentIndex, isActive } = get();
    if (!isActive || queue.length === 0) return null;
    return queue[currentIndex] ?? null;
  },

  getUpNext: () => {
    const { queue, currentIndex, isActive } = get();
    if (!isActive) return null;
    return queue[currentIndex + 1] ?? null;
  },

  getProgress: () => {
    const { queue, currentIndex } = get();
    return { current: currentIndex + 1, total: queue.length };
  },
}));